### ISSUE TITLE
TypeError: 'DataFrame' object is not callable

### ISSUE THREAD

**Issue by dk27dineshkumar** [joelz575/swatplus-tinamit-coupling#1]
D:\swatplus-tinamit-coupling-main>python UsaBasinModel.py
swatplus/build/bin/swatplus_exe
Traceback (most recent call last):
  File "UsaBasinModel.py", line 40, in <module>
    vensim = [ModeloPySD("BaseLineScenario.mdl"), ModeloPySD("45SubsidyScenario.mdl"),
  File "C:\Users\Admin\anaconda3\lib\site-packages\tinamit\envolt\mds\pysd\_envolt.py", line 27, in __init__
    super().__init__(variables=_gen_vars(símismo.mod), nombre=nombre)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tinamit\envolt\mds\pysd\_envolt.py", line 113, in _gen_vars
    for i, f in mod.doc().iterrows():
TypeError: 'DataFrame' object is not callable

**Comment by joelz575** [comment]
Thank you for pointing out this error!

The issue is with the pre-requisites as multiple packages had major updates.
The newly commited `requirements.txt` file contains the packages that need to be installed.
You can use:
`pip install -r requirements.txt`
to install all the required packages.
I have updated the poetry requirements as well so they should now also be functional.

Furthermore, the swatplus_exe file will run on Ubuntu systems, not on Windows, so to use it you'll need to be using an Ubuntu or other Linux system.

Hope this helps,
Joel
