### ISSUE TITLE
Code Run Help

### ISSUE THREAD

**Issue by jeremyluhaha** [joelz575/swatplus-tinamit-coupling#2]
Dear Mr Harms
     When I tried to run the code, I found that it got stuck in a loop while running. I don't know how to solve it, so I asked for your help. This loop is shown below：
    for run in range(model_runs):
        try:
            swatPlus = ModeloSWATPlus('Usa_Basin_model', lte_hru=False, cha=False, sd_ch=True)
            swatPlus.agrupar_usos_del_suelo([2, 3, 7, 8, 9])
     I would greatly appreciate it if you were willing to help me.

**Comment by joelz575** [comment]
Thank you for letting me know, I will get back to you tomorrow regarding this after I investigate!


All the best,
Joel
________________________________
From: jeremyluhaha ***@***.***>
Sent: Sunday, March 17, 2024 00:35
To: joelz575/swatplus-tinamit-coupling ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [joelz575/swatplus-tinamit-coupling] Code Run Help (Issue #2)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Dear Mr Harms
When I tried to run the code, I found that it got stuck in a loop while running. I don't know how to solve it, so I asked for your help. This loop is shown below：
for run in range(model_runs):
try:
swatPlus = ModeloSWATPlus('Usa_Basin_model', lte_hru=False, cha=False, sd_ch=True)
swatPlus.agrupar_usos_del_suelo([2, 3, 7, 8, 9])
I would greatly appreciate it if you were willing to help me.

**Comment by jeremyluhaha** [comment]
OK, Thank you for your generosity.

**Comment by joelz575** [comment]
Hello Jeremy,
Please excuse the late reply!

So in general I don't understand how there could be an infinite loop here because the `model_runs` are the limiting factor in the for loop, so by definition there can't be more repetitions than the value specified in `model_runs` (which I believe is set to 10 by default). Try to lower this value to 2 for example, this will more quickly return results as the 10 runs usually take quite long time.

Another note, sometimes errors will occur as land-use of the same HRU is re-allocated multiple times in succession, due to the random process by which it is allocated. This will be fixed soon, once I have some time to come back to this project. So for now, if an error occurs during execution, simply run it again from the beginning.

Please let me know if you have any further questions or problems!

All the best,
Joel

**Comment by jeremyluhaha** [comment]
Dear Mr Harms
Sorry to bother you again.
I tried to change the value to 2, but still did not output the result. To see where the problem occurred, I added some print functions and found that the code got stuck in this step during runtime without any errors. I will attach screenshots.
All the best
Jeremy
<img width="656" alt="problem" src="https://github.com/joelz575/swatplus-tinamit-coupling/assets/97999276/a285a65f-4bd6-434f-8408-447d7a84ec82">

**Comment by joelz575** [comment]
No worries!
In that case, could you let me know which operating system you are using and would you be able to figure out which line in the SWATWrapper.py​ file you are stuck at? (i.e. check the --init-- function of the ModeloSWATPlus class)

Joel

________________________________

**Comment by jeremyluhaha** [comment]
I'm using winows11.It seems that there is a problem in this function.[
<img width="730" alt="problem2" src="https://github.com/joelz575/swatplus-tinamit-coupling/assets/97999276/8e25dc61-0f2e-447c-988d-b88039af192c">
](url)

**Comment by joelz575** [comment]
Yes that makes sense, there is unfortunately no working Windows version of the coupleable SWAT+ exe.
That is the reason why it fails in this line I believe because it is trying to establish the connection with the .exe file but it is not compiled for Windows.

At the moment it unfortunately it only works for Linux operating systems.
You may be able to use a virtual Linux machine or a cloud server that runs on Linux and try to run the code there?

I am very sorry about this, however, we spent about 2 years trying to get it to work on Windows during development but had to scratch that version unfortunately. Getting a MacOS version working wouldn't be too difficult, I just didn't have access to one and the compiling would work slightly different than for Linux. For Windows however, we need to use other packages for the socket connectivity and would have to adapt the code to those, as well as there being some compiler issues on top of that.

If you have any further question don't hesitate to e-mail me!

All the best,
Joel

**Comment by jeremyluhaha** [comment]
Thanks for helping me, I will try this in virtual linux machine.


Wishing you a happy life,
Jeremy

发自我的iPhone


------------------ Original ------------------
From: joelz575 ***@***.***&gt;
Date: Sat,Mar 23,2024 0:19 PM
To: joelz575/swatplus-tinamit-coupling ***@***.***&gt;
Cc: jeremyluhaha ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [joelz575/swatplus-tinamit-coupling] Code Run Help (Issue #2)





 
Yes that makes sense, there is unfortunately no working Windows version of the coupleable SWAT+ exe.
 That is the reason why it fails in this line I believe because it is trying to establish the connection with the .exe file but it is not compiled for Windows.
 
At the moment it unfortunately it only works for Linux operating systems.
 You may be able to use a virtual Linux machine or a cloud server that runs on Linux and try to run the code there?
 
I am very sorry about this, however, we spent about 2 years trying to get it to work on Windows during development but had to scratch that version unfortunately. Getting a MacOS version working wouldn't be too difficult, I just didn't have access to one and the compiling would work slightly different than for Linux. For Windows however, we need to use other packages for the socket connectivity and would have to adapt the code to those, as well as there being some compiler issues on top of that.
 
If you have any further question don't hesitate to e-mail me!
 
All the best,
 Joel
